# Generated by Django 5.0.4 on 2024-05-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=25)),
                ('status_type', models.CharField(choices=[('REGULAR', 'REGULAR'), ('INITIAL', 'INITIAL'), ('FINAL', 'FINAL')], default='REGULAR', max_length=10)),
            ],
        ),
    ]
