repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint --fail-under=-15 *.py
        language: system
        types: [python]
        args:
            [
                "-rn",
                "-sn"
            ]
    -   id: yapf
        name: yapf
        entry: yapf  --in-place *.py
        language: system