version: '3.8'

services:
  app:
    build:
      context: ../app/
    ports:
      - "80:80"
    depends_on:
      - api
  
  api:
    build:
      context: ../backend/
    ports:
      - "8000:8000"
