# Generated by Django 5.0.4 on 2024-05-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
